catch {::common::set_param -quiet hls.xocc.mode csynth};
catch {::common::set_param -quiet hls.xocc.enable_rule_check_client 1};
# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project vadd
set_top vadd
add_files "/proj/xhdhdstaff3/rsarkari/scout/ScoutExamples/101_hello_world/src/vadd.cpp" -cflags " -I /proj/xhdhdstaff3/rsarkari/scout/ScoutExamples/101_hello_world/src "
open_solution solution
set_part xcu200-fsgd2104-2-e
create_clock -period 300MHz -name default
config_sdx -target xocc -optimization_level $xocc_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
config_export -format ip_catalog -ipname vadd
csynth_design
export_design
close_project
puts "Vivado HLS completed successfully"
exit
