#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 15 10:40:32 PDT 2024
# SW Build 5037991 on Sun Apr 14 16:43:25 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
[ -z "$LIBRARY_PATH" ] && export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu || export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
set -Eeuo pipefail

export xv_cxl_lib_path="/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1/data/xsim"
export xv_cxl_ip_path="$xv_cxl_lib_path/ip"
export xv_cpt_lib_path="/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1/data/simmodels/xsim/2024.1/lnx64/9.3.0/systemc/protected"
xv_ext_lib_path="/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1/data/simmodels/xsim/2024.1/lnx64/9.3.0/ext"
xv_lib_path="/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1/lib/lnx64.o/Ubuntu/22:/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1/lib/lnx64.o/Ubuntu:/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1/lib/lnx64.o"

xv_ref_path=${VIVADO_LOC:-"/proj/xbuilds/SWIP/2024.1_0414_2055/installs/lin64/Vivado/2024.1"}
xv_lib_path="$xv_ref_path/lib/lnx64.o/Default:$xv_ref_path/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$xv_ref_path/data/simmodels/xsim/2024.1/lnx64/9.3.0/ext/protobuf:$xv_ref_path/data/xsim/ip/xscl:$xv_ref_path/data/xsim/ip/sim_qdma_cpp_v1_0:$xv_ref_path/data/xsim/ip/xtlm_ipc_v1_0:$xv_ref_path/data/xsim/ip/sim_qdma_sc_v1_0:$xv_ref_path/data/xsim/ip/xtlm_simple_interconnect_v1_0:$xv_ref_path/data/xsim/ip/xtlm_ap_ctrl_v1_0:$xv_ref_path/data/xsim/ip/sim_ddr_v1_0:$xv_ref_path/data/xsim/ip/common_cpp_v1_0:$xv_ref_path/data/xsim/ip/common_rpc_v1:$xv_ref_path/data/xsim/ip/xtlm:$xv_ref_path/data/xsim/ip/emu_perf_common_v1_0:$LD_LIBRARY_PATH

# simulate design
echo "xsim pfm_top_wrapper_behav -key {Behavioral:sim_1:Functional:pfm_top_wrapper} -tclbatch pfm_top_wrapper.tcl -protoinst "protoinst_files/bd_f615.protoinst" -protoinst "protoinst_files/bd_2b97.protoinst" -protoinst "protoinst_files/bd_d216.protoinst" -protoinst "protoinst_files/pfm_dynamic.protoinst" -protoinst "protoinst_files/bd_448f.protoinst" -protoinst "protoinst_files/bd_387c.protoinst" -protoinst "protoinst_files/pfm_top.protoinst" -log simulate.log $*"
xsim pfm_top_wrapper_behav -key {Behavioral:sim_1:Functional:pfm_top_wrapper} -tclbatch pfm_top_wrapper.tcl -protoinst "protoinst_files/bd_f615.protoinst" -protoinst "protoinst_files/bd_2b97.protoinst" -protoinst "protoinst_files/bd_d216.protoinst" -protoinst "protoinst_files/pfm_dynamic.protoinst" -protoinst "protoinst_files/bd_448f.protoinst" -protoinst "protoinst_files/bd_387c.protoinst" -protoinst "protoinst_files/pfm_top.protoinst" -log simulate.log $*

